# parameters_ua.py
# =====================================================================
# Ultrasonic-attenuation-specific parameters ONLY.
# SC parameters (Tc, Delta0) are loaded from the Tc-vs-VSO results,
# NOT hardcoded here.
# =====================================================================

from pathlib import Path

# ── Physical constants (natural units) ───────────────────────────────
t     = 1.0
eta   = 1.0    # coherence factor sign: +1 (Case I) or -1 (Case II)
B     = 1.0    # coupling constant
hbar  = 1.0
omega = 0.7    # phonon energy ℏω
kB    = 1.0

# ── Target electron density ───────────────────────────────────────────
n_target = 1.8850

# ── DOS broadening ────────────────────────────────────────────────────
sigma = 0.05   # Gaussian broadening parameter

# ── k-grid (finer than Tc code) ───────────────────────────────────────
Nk_ua = 200    # ultrasonic code uses 200 × 200

# ── Energy grid ───────────────────────────────────────────────────────
NE         = 500
E_grid_min = -6.0
E_grid_max =  6.0

# ── Scan settings ─────────────────────────────────────────────────────
T_SCAN_POINTS   = 2000          # temperature grid for T-sweep
T_SCAN_OVERHEAD = 1.4           # T_max = overhead * max(Tc)
T_FRACS_DEFAULT = (0.3, 0.5, 0.7, 0.9)   # for VSO scan

# ── VSO list for the detailed temperature sweep ───────────────────────
VSO_SWEEP_LIST  = [0.0000, 0.4082, 0.8000]

# ── Paths ─────────────────────────────────────────────────────────────
# Where to find the Tc-vs-VSO results generated by the previous code
SC_PARAMS_JSON = Path("../sc_params/results/tc_vs_vso.json")
SC_PARAMS_NPZ  = Path("../sc_params/results/Tc_vs_VSO.npz")

# Where to save ultrasonic results
UA_RESULTS_DIR = Path("results")